import Head from "next/head";
import Image from "next/image";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-slate-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="mb-12 flex justify-between py-10 dark:text-white ">
            <h1 className="font-burtons text-xl">Jhondel</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="ml-8 rounded-md bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="p-10 text-center">
            <h2 className="py-2 text-5xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
              Dimitri Marco
            </h2>
            <h3 className="py-2 text-2xl dark:text-white md:text-3xl">
              Developer and designer
            </h3>
            <p className="text-md mx-auto max-w-xl py-5 leading-8 text-slate-800 dark:text-slate-200 md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="flex justify-center gap-16 py-3 text-5xl text-slate-600 dark:text-slate-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="relative mx-auto mt-20 h-80 w-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
              <Image src={deved} fill className="object-cover" alt="" />
            </div>
          </div>
        </section>
        {/* section 2 */}
        <section>
          <div className="">
            <h3 className="py-1 text-3xl dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-slate-800 dark:text-slate-200">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-slate-800 dark:text-slate-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className="gap-10 lg:flex">
            <div className="my-10 flex-1 rounded-xl p-10 text-center  shadow-lg dark:bg-white">
              <Image
                src={design}
                width={100}
                height={100}
                alt=""
                className="mx-auto"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-slate-800">Photoshop</p>
              <p className="py-1 text-slate-800">Illustrator</p>
              <p className="py-1 text-slate-800">Figma</p>
              <p className="py-1 text-slate-800">Indesign</p>
            </div>

            <div className="my-10 flex-1 rounded-xl p-10 text-center shadow-lg dark:bg-white">
              <Image
                src={code}
                width={100}
                height={100}
                alt=""
                className="mx-auto"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make
                it a reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-slate-800">Photoshop</p>
              <p className="py-1 text-slate-800">Illustrator</p>
              <p className="py-1 text-slate-800">Figma</p>
              <p className="py-1 text-slate-800">Indesign</p>
            </div>

            <div className="my-10 flex-1 rounded-xl p-10 text-center shadow-lg dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt=""
                className="mx-auto"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-slate-800">Photoshop</p>
              <p className="py-1 text-slate-800">Illustrator</p>
              <p className="py-1 text-slate-800">Figma</p>
              <p className="py-1 text-slate-800">Indesign</p>
            </div>
          </div>
        </section>
        {/* section 3 */}
        <section className="py-10">
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-slate-800 dark:text-slate-200">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-slate-800 dark:text-slate-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="relative flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="flex-1 basis-1/3 ">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web1}
                alt=""
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web2}
                alt=""
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web3}
                alt=""
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web4}
                alt=""
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web5}
                alt=""
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                style={{ height: "100%", width: "100%" }}
                src={web6}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
